name: wakatime-stats

on: push

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          USERNAME: kekotek # optional, it will automatically use the username of the owner of the repository who's executing the workflow.
          SHOW_COMMIT: "True"
